map:
  resolution: 0.1
  map_x_l: -20.0
  map_x_u: 20.0
  map_y_l: -20.0
  map_y_u: 20.0

planning: 
  step_size: 0.3
  h_surf_car: 0.7
  w_flatness: 1000
  w_slope: 0.01
  w_sparsity: 1
  w_fit_plane: 1.0
  radius_fit_plane: 0.6
  ratio_max: 0.1
  ratio_min: 0.04
  conv_thre: 0.1152



